function getIdiomas() {
  return [
    { label: 'Português', value: 'pt' },
    { label: 'English', value: 'en' },
    { label: 'Español', value: 'es' },
    { label: 'العربية', value: 'ar' },
    { label: '中文', value: 'zh' },
    { label: 'Nederlands', value: 'nl' },
    { label: 'Français', value: 'fr' },
    { label: 'Deutsch', value: 'de' },
    { label: 'Ελληνικά', value: 'el' },
    { label: 'עברית', value: 'he' },
    { label: 'हिन्दी', value: 'hi' },
    { label: 'Italiano', value: 'it' },
    { label: '日本語', value: 'ja' },
    { label: 'മലയാളം', value: 'ml' },
    { label: 'मराठी', value: 'mr' },
    { label: 'Norsk', value: 'no' },
    { label: 'Română', value: 'ro' },
    { label: 'Русский', value: 'ru' },
    { label: 'Svenska', value: 'sv' },
    { label: 'தமிழ்', value: 'ta' },
    { label: 'తెలుగు', value: 'te' },
    { label: 'Українська', value: 'uk' }
  ];
}

function getPaises() {
  return [
    { label: 'Argentina', value: 'ar' },
    { label: 'Australia', value: 'au' },
    { label: 'Österreich', value: 'at' },
    { label: 'België / Belgique', value: 'be' },
    { label: 'Brasil', value: 'br' },
    { label: 'България', value: 'bg' },
    { label: 'Canada', value: 'ca' },
    { label: '中国', value: 'cn' },
    { label: 'Colombia', value: 'co' },
    { label: 'Cuba', value: 'cu' },
    { label: 'Česká republika', value: 'cz' },
    { label: 'مصر', value: 'eg' },
    { label: 'France', value: 'fr' },
    { label: 'Deutschland', value: 'de' },
    { label: 'Ελλάδα', value: 'gr' },
    { label: '香港', value: 'hk' },
    { label: 'Magyarország', value: 'hu' },
    { label: 'भारत', value: 'in' },
    { label: 'Indonesia', value: 'id' },
    { label: 'Ireland', value: 'ie' },
    { label: 'ישראל', value: 'il' },
    { label: 'Italia', value: 'it' },
    { label: '日本', value: 'jp' },
    { label: 'Latvija', value: 'lv' },
    { label: 'Lietuva', value: 'lt' },
    { label: 'Malaysia', value: 'my' },
    { label: 'México', value: 'mx' },
    { label: 'المغرب', value: 'ma' },
    { label: 'Nederland', value: 'nl' },
    { label: 'New Zealand', value: 'nz' },
    { label: 'Nigeria', value: 'ng' },
    { label: 'Norge', value: 'no' },
    { label: 'Pilipinas', value: 'ph' },
    { label: 'Polska', value: 'pl' },
    { label: 'Portugal', value: 'pt' },
    { label: 'România', value: 'ro' },
    { label: 'Россия', value: 'ru' },
    { label: 'السعودية', value: 'sa' },
    { label: 'Србија', value: 'rs' },
    { label: 'Singapore', value: 'sg' },
    { label: 'Slovensko', value: 'sk' },
    { label: 'Slovenija', value: 'si' },
    { label: 'South Africa', value: 'za' },
    { label: '대한민국', value: 'kr' },
    { label: 'Sverige', value: 'se' },
    { label: 'Schweiz / Suisse / Svizzera', value: 'ch' },
    { label: '台灣', value: 'tw' },
    { label: 'ประเทศไทย', value: 'th' },
    { label: 'Türkiye', value: 'tr' },
    { label: 'Україна', value: 'ua' },
    { label: 'الإمارات', value: 'ae' },
    { label: 'United Kingdom', value: 'gb' },
    { label: 'United States', value: 'us' },
    { label: 'Venezuela', value: 've' },
    { label: 'Việt Nam', value: 'vn' }
  ];
}

function getTopicos() {
  return [
    {label: 'Últimas notícias', value: 'breaking-news'}, 
    {label: 'Mundo', value: 'world'},
    {label: 'Nacional', value: 'nation'},
    {label: 'Negócios', value: 'business'},
    {label: 'Tecnologia', value: 'technology'},
    {label: 'Entretenimento', value: 'entertainment'},
    {label: 'Esportes', value: 'sports'},
    {label: 'Ciência', value: 'science'},
    {label: 'Saúde', value: 'health'}
  ]
}